dist: bionic

language: python

python: 3.7

services:
  - docker

jobs:
  include:
    - stage: Run tests
      name: QGIS Desktop
      install:
        - cd .docker
        - ./start.sh
      script:
        - ./exec.sh