services:
    - docker

sudo: false

env:
  global:
    - IMAGE=qgis/qgis

  matrix:
    - QGIS_VERSION_TAG=release-3_4
    # - QGIS_VERSION_TAG=release-3_10
    - QGIS_VERSION_TAG=latest

branches:
  only:
    - master

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/qgis_drain_sewer_visual_inspection -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  - sleep 10
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh qgis_drain_sewer_visual_inspection"

script:
  - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh qgis_drain_sewer_visual_inspection.test_runner.test_package"

notifications:
  email:
    - etrimaille@3liz.com
