dist: bionic

language: python

python: 3.7

services:
  - docker

jobs:
  include:
    - stage: Run tests
      name: QGIS Desktop
      install:
        - cd .docker
        - ./start.sh
      script:
        - ./exec.sh

    - stage: Push translations to Transifex
      if: branch = master
      install:
        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      script: qgis-plugin-ci push-translation ${TX_TOKEN}
