version: '3'

services:
  qgis:
    image: qgis/qgis:release-3_4
    container_name: qgis
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ../drain_sewer_visual_inspection:/tests_directory/drain_sewer_visual_inspection
    environment:
      # - DISPLAY=unix$DISPLAY
      - DISPLAY=:99