name: 🗺 Translations

on:
  push:
    paths:
      - '**.py'

jobs:
  push:
    name: Push to Transifex
    runs-on: ubuntu-latest
    if: github.repository == '3liz/qgis_drain_sewer_visual_inspection'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.8

    - name: Install qgis-plugin-ci
      run: python -m pip install -r requirements/requirements-release.txt

    - name: Push to Transifex
      run: qgis-plugin-ci push-translation ${{ secrets.TRANSIFEX_TOKEN }}
